### ISSUE TITLE
NYU Dataset

### ISSUE THREAD

**Issue by LorenzoPapa1699806** [shariqfarooq123/AdaBins#27]
Dear authors, 

Can you please confirm that the (NYU) Test and Train datasets are the same used in your old paper titled "High-Quality Monocular Depth Estimation via Transfer Learning"? 

Thank you.

**Comment by shariqfarooq123** [comment]
Hi,

This work uses Eigen Train/Test split which is the same as the work you mentioned. But this project uses Raw depth maps instead of completed ones. Also, some bad samples are eliminated from the training set. You can refer to [BTS repo](https://github.com/cogaplex-bts/bts) for the data preparation for both NYU and KITTI datasets.

**Comment by shariqfarooq123** [comment]
Checkout the minor correction
