### ISSUE TITLE
Realtime Distance Calculation

### ISSUE THREAD

**Issue by saiteja1904** [shariqfarooq123/AdaBins#34]
Hi I am trying to implement this model  along with yolo Y5 ,realtime by using cameras on a motorbike to calculate the distance of vehicles,while riding the bike, but the accuracy is very bad is there any way to improve the accuracy ?,and is it possible to implement this on Jetson Nano ?

**Comment by I3aer** [comment]
Hi,
There is a paper that examines "How do NNs see depth in single images?" published by ICCV. According to that paper, depth estimation networks cannot completely detect and account for changes in camera pose. Since depth estimation depends on camera pose, monocular depth estimation networks over-/under-estimates depths from images under change in camera pose. Unfortunately, you cannot obtain reliable results unless you fine-tune monocular depth estimation networks to your dataset.
